#!/usr/bin/env bash
# This script is displaying  numbers from 1 to 100.

for i in {1..100}
do
	if ! ((i%15))
	then
		echo FizzBuzz
	elif ! ((i%5))
	then
		echo Buzz
	elif ! ((i%3))
	then
		echo Fizz
	else
		echo $i
	fi
done
